name: End-to-end tests

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    cypress-run:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Env
              env:
                  SHIPPO_KEY: ${{ secrets.SHIPPO_KEY }}
                  SHIPPO_TEST: ${{ secrets.SHIPPO_TEST }}
              run: |
                  echo "SHIPPO_KEY=${SHIPPO_KEY}" >> $GITHUB_ENV
                  echo "SHIPPO_TEST=${SHIPPO_TEST}" >> $GITHUB_ENV
            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  build: npm run build
                  start: npm start
